// Generated by CoffeeScript 1.10.0
(function() {
  var _,
    slice = [].slice;

  _ = {};

  _.upperFirst = require('lodash.upperfirst');

  _.camelCase = require('lodash.camelcase');

  _.isString = require('lodash.isstring');

  _.isArray = require('lodash.isarray');

  module.exports = {
    bootstrap: function() {
      var accessors;
      accessors = this;
      Function.prototype.getter = function() {
        var fields;
        fields = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return accessors.getter.apply(accessors, [this.prototype].concat(slice.call(fields))).bind(accessors);
      };
      Function.prototype.setter = function() {
        var fields;
        fields = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return accessors.setter.apply(accessors, [this.prototype].concat(slice.call(fields))).bind(accessors);
      };
      return Function.prototype.accessor = function() {
        var fields;
        fields = 1 <= arguments.length ? slice.call(arguments, 0) : [];
        return accessors.accessor.apply(accessors, [this.prototype].concat(slice.call(fields))).bind(accessors);
      };
    },
    getter: function() {
      var field, fields, i, len, name, obj, prefix, type;
      obj = arguments[0], fields = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      for (i = 0, len = fields.length; i < len; i++) {
        field = fields[i];
        if (_.isString(field)) {
          this._createGetter(obj, field);
        } else {
          if (_.isArray(field)) {
            prefix = field[0], name = field[1];
          } else {
            prefix = field.prefix, type = field.type, name = field.name;
          }
          if (prefix == null) {
            prefix = (function() {
              switch (type) {
                case 'bool':
                  return 'is';
                default:
                  return 'get';
              }
            })();
          }
          this._createGetter(obj, field, prefix);
        }
      }
    },
    reader: this.getter,
    setter: function() {
      var field, fields, i, len, name, obj, prefix;
      obj = arguments[0], fields = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      for (i = 0, len = fields.length; i < len; i++) {
        field = fields[i];
        if (_.isString(field)) {
          this._createSetter(obj, field);
        } else {
          if (_.isArray(field)) {
            prefix = field[0], name = field[1];
          } else {
            name = field.name;
          }
          this._createSetter(obj, name);
        }
      }
    },
    writer: this.setter,
    accessor: function() {
      var fields, obj;
      obj = arguments[0], fields = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      this.reader.apply(this, [obj].concat(slice.call(fields)));
      return this.writer.apply(this, [obj].concat(slice.call(fields)));
    },
    _createGetter: function(obj, field, prefix) {
      if (prefix == null) {
        prefix = 'get';
      }
      return obj[this._getAccessorMethodName(field, prefix)] = function() {
        return obj[field];
      };
    },
    _createSetter: function(obj, field, prefix) {
      if (prefix == null) {
        prefix = 'set';
      }
      return obj[this._getAccessorMethodName(field, prefix)] = function(newValue) {
        return obj[field] = newValue;
      };
    },
    _getAccessorMethodName: function(field, prefix) {
      return "" + prefix + (_.upperFirst(_.camelCase(field)));
    }
  };

}).call(this);
